### ISSUE TITLE
first connection to IDE after flash weio_recovery returns error message

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#101]
![screen shot 2015-01-26 at 17 49 22](https://cloud.githubusercontent.com/assets/9677805/5904441/b3928c5a-a588-11e4-9e04-aa22c1cf21fe.png)

After a soft reset connection to IDE works normally

**Comment by drasko** [comment]
Yes, this is really a bug. I have no idea for now where it comes from.

Easiest solution is to add a reboot on first re-flash. Might be that jffs formating of mtd parts confusing server... Maybe we have to force just restart of WeIO app on first re-flash...

**Comment by nmarcetic** [comment]
I also propose reboot, ssh is also down.

**Comment by drasko** [comment]
I would avoid reboot for the first version. We will investigate for the next major release (platform + app update). For minor releases it is only app update, so this bug will not be visible.

**Comment by ks156** [comment]
I built a new binary image yesterday, and I've noticed that all is working fine at first boot. No Internal Server Error, ssh OK after setting the user account and password, and so on.
I'll test again with the official release to see if the error is still here.

Could it be due to the binary size ? Mine is a bit bigger than the official release.

I can share my binary file if someone want to try.

**Comment by manuIO** [comment]
I've tested yesterday and I had the same error.

**Comment by drasko** [comment]
This might be due to the way scripts are init in rcS. Last one is weio_run
(START=99,
https://github.com/nodesign/weio/blob/master/openWrt/files/etc/init.d/weio_run#L4),
but I am not so sure that network is ready at this point.

Also, WeIO is actualy always started by this script:
https://github.com/nodesign/weio/blob/master/scripts/run_weio.sh. I.e.
initd service starts this script, and this script has while(1) loop to
restart Tornado in case it breaks (otherwise user will never get their hand
on IDE once it breaks).

Maybe there is something worng in this script...

**Comment by ks156** [comment]
This problem seems related to jffs2, and don't occurs with all binaries.

**Comment by ks156** [comment]
Everything looks fine with Chaos Calmer. First boot is OK

**Comment by drasko** [comment]
:clap:

**Comment by ks156** [comment]
Fixed by v1.2
