### ISSUE TITLE
Cant connect to network in sta mode

### ISSUE THREAD

**Issue by Pinciukas1991** [nodesign/weio#142]
Title says everything. When i try to conenct to my home network it fails, sta LED indicator doesnt light up. But when  check wireless.sta file i see that all options are set correctly (ssid, encryption et.).

**Comment by ks156** [comment]
When you change the Wifi settings from the IDE, the LEDs starts to blink, and the board tries to connect to the specified STA network. This may takes time. If it fails to connect, it will automatically restart its AP mode.
How did you change the wireless setting ? From the IDE ?

**Comment by Pinciukas1991** [comment]
Everything happened as you said )) it started to blink, sta failed, and at the end jus AP led was on. Yes, from IDE.

**Comment by ks156** [comment]
That's strange. You may maybe try to restart the board and try again. 
Can you also tell what's the security protocol of your access point (WEP / WPA / …) ?

**Comment by Pinciukas1991** [comment]
yea i found a problem . thanks a lot. But it rises another question, is it possible and if it is,  how to set ap and sta modes to be at the same tme, cause now is only ap or sta. And another is it possible to conneect into IDE when  just sta mode is on?

**Comment by ks156** [comment]
Ok, great. Can you briefly explain what the problem was. It may help other poeple.

You can't use the Wifi in AP and STA modes in the same time. When you're on STA mode, you can connect to the IDE with the URL http://*board_name_you_set*.local:8080. If you're on Windows, you have to install *Bonjour* : http://support.apple.com/kb/DL999. Otherwise, you can also connect to the board via its IP address, if you know it.
You will probably find some interresting info in the *getting started* page here : http://we-io.net/doc/gettingStarted.html#connect-to-weio-and-first-time-setup

**Comment by Pinciukas1991** [comment]
The problem was very silly and it was ofc my mistake. I mistyped network interface. Back to sta mode. I can from my computer ping board IP , but i cant ping board:8080 (same goes with board.name.local:8080) .  Because i want to update my board and i don't for this moment know how (apt-get , yum commans dornd found, opkg also seems to struggle ) :D

**Comment by ks156** [comment]
Ok. The best is to connect here : https://gitter.im/nodesign/weio
It would be easier to help you.
Btw, this issue can be closed I guess.

**Comment by drasko** [comment]
@ks156 actually - you can have both AP and STA mode on WeIO :). But this is **not** supported buy our IDE now, as it is not normal usecase.

Take a look here:
http://lwn.net/Articles/321690/
https://wireless.wiki.kernel.org/en/users/documentation/iw/vif
http://www.candelatech.com/vsta.php

AR9331 has ath9k driver support, and this is one of the most elaborated (and open) Linux driver. That's why these crazy stuff like virtual radios are possible. So yes - you can make mesh networks with WeIO. I tried it - it works nicely :). Just have in mind that bandwidth is split between virtual radios.

Point is that we did not really want to have AP always on - firstly because it is used only for config, and otherwise it would eat up half of STA bandwidth. So it is better (and easier) to use only one mode for now, and let to people with more Linux networking knowledge do their configuration as they like.

@Pinciukas1991 you have a hidden network right (otherwise it would be present in pull-down menu)?

To ping the board by `<myboard>.local` you have to have Bonjour support on you PC.  I don't know which OS you use, but please refer to official WeIO _Getting Started_: http://we-io.net/doc/gettingStarted.html#prerequisites-install-on-your-pc

What do you really want to update on the board? WeIO updates are done automatically, from IDE. But we are currently on v1.0 for all the boards.

Otherwise - `opkg` should be used. But here you enter in OpenWrt  waters, so you should refer to OpenWrt documentation: http://wiki.openwrt.org/doc/techref/opkg

Shortly:
```bash
opkg update
opkg install <myPackage)
```
should do the job.

**Comment by Pinciukas1991** [comment]
Thanks guys for those quick answers , u r very helpful. I managed to connect and update now this board finally ..)) 
Drasko , thanks for explanations why we dont need both ap and sta at the same time.

**Comment by drasko** [comment]
Closing the issue.
