### ISSUE TITLE
weioRunner.py prints traces on program STOP (UPER reset)

### ISSUE THREAD

**Issue by drasko** [nodesign/weio#168]
WeIO user server launched 2015-04-16 21:55:47
WeIO user program stoped. It was runnig since : 2015-04-16 21:55:47
weioRunner.py: UPER API: Unrecoverable serial port writing error, dying. 
weioRunner.py: UPER API: Unrecoverable serial port writing error, dying. 
weioRunner.py: UPER API: Unrecoverable serial port writing error, dying.

**Comment by ks156** [comment]
Drasko, this problem occurs with all examples ?

**Comment by ks156** [comment]
This message is generated here : https://github.com/nodesign/weio/blob/master/IoTPy/pyuper/ioboard.py#L212
It's here that the data is sent to the LPC. What I suspect is:
- When you click on "STOP", the reset command is sent (https://github.com/nodesign/weio/blob/master/IoTPy/pyuper/ioboard.py#L259-L263)
- This command reset the LPC, so /dev/ttyACM0 will not be available anymore
- Some commands (from where, why) are still sent by the API, and then the error occurs.

That's the reason why it's interesting to know if it occurs with all examples, or only with those that send many commands (like this one for example https://github.com/nodesign/weio/blob/master/examples/digital/pwmWrite_PY/main.py).

In any case, I think this bug can be fixed by stopping completely all the process before sending the reset command.

**Comment by drasko** [comment]
More or less all I tried last night... I do not remember.

Take care that there not only the user processes sending data to UPER, but user Tornado also, through user agent for JS frontend.
 Point I s that user Tornado starts/stops execution threads, but itself acts as the server for HTML GUI and intercepts and executes JS genericMessage(). Even if you stop all the user processes, if you keep browser open and bombard user Tornado with for example pwmWrite(), it will keep sending these messages to UPER until STOP button is presses (after which user Tornado will ignore these messages from browser).

**Comment by ks156** [comment]
If ok, can be closed
